name: revert-push
  
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Branch to revert latest commit'
        required: true
        default: 'master'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com
          git reset --hard HEAD~1
          git push --force
