name: test2-revert-action
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to revert latest commit'
        required: true
        default: 'master'

jobs:
  test2-revert-action:
    runs-on: ubuntu-latest
    steps: 
      - name: Revert Push
        uses: lcenchew/revert-push@v0.0.1
